use super::*;
use crate::crush::types::{
    BucketAlgorithm, BucketData, CrushBucket, CrushRule, CrushRuleStep, RuleType,
};

fn map() -> CrushMap {
    let mut map = CrushMap::new();
    map.max_devices = 4;
    map.max_buckets = 2;
    map.buckets = [(-1, 2, vec![-2]), (-2, 1, vec![0, 1, 2, 3])]
        .into_iter()
        .map(|(id, bucket_type, items)| {
            let size = items.len() as u32;
            Some(CrushBucket {
                id,
                bucket_type,
                alg: BucketAlgorithm::Straw2,
                hash: 0,
                weight: 0x40000,
                size,
                items,
                data: BucketData::Straw2 {
                    item_weights: vec![0x40000 / size; size as usize],
                },
            })
        })
        .collect();
    map.rules = vec![Some(CrushRule {
        rule_id: 0,
        rule_type: RuleType::Erasure,
        steps: vec![
            CrushRuleStep {
                op: RuleOp::Take,
                arg1: -2,
                arg2: 0,
            },
            CrushRuleStep {
                op: RuleOp::ChooseIndep,
                arg1: 1,
                arg2: 0,
            },
            CrushRuleStep {
                op: RuleOp::Emit,
                arg1: 0,
                arg2: 0,
            },
        ],
    })];
    map
}

#[test]
fn firstn_shifts_signed_parent_retry_like_ceph() {
    let map = map();
    // Generated by reference/mapper-types.c with pinned Quincy and Tentacle.
    for (parent_r, expected) in [(i32::MIN, [0, 2, 0, 0, 1]), (-1, [2, 2, 1, 1, 0])] {
        for (x, leaf) in [0, 1, i32::MAX, i32::MIN, -1].into_iter().zip(expected) {
            let mut out = [CRUSH_ITEM_NONE];
            let mut leaves = [CRUSH_ITEM_NONE];
            let count = crush_choose_firstn(
                &map,
                -1,
                x,
                1,
                1,
                &mut out,
                0,
                &[0x10000; 4],
                1,
                1,
                0,
                0,
                2,
                1,
                Some(&mut leaves),
                parent_r,
                None,
                None,
            )
            .unwrap();
            assert_eq!(count, 1);
            assert_eq!(leaves, [leaf], "x={x}, parent_r={parent_r}");
        }
    }
}

#[test]
fn retry_budget_and_fallback_bound_wrap_like_ceph() {
    let mut map = map();
    map.choose_total_tries = u32::MAX;
    let mut result = Vec::new();
    crush_do_rule(&map, 0, 0, &mut result, 1, &[0x10000; 4]).unwrap();
    assert_eq!(result, [CRUSH_ITEM_NONE]);
    let mut out = [CRUSH_ITEM_NONE];
    let count = crush_choose_firstn(
        &map,
        -2,
        0,
        1,
        0,
        &mut out,
        0,
        &[0; 4],
        1,
        1,
        0,
        u32::MAX,
        0,
        0,
        None,
        0,
        None,
        None,
    )
    .unwrap();
    assert_eq!(count, 0);
}

#[test]
fn invalid_shift_and_unrepresentable_mapper_count_return_errors() {
    let map = map();
    let mut out = [CRUSH_ITEM_NONE];
    let mut leaves = [CRUSH_ITEM_NONE];
    assert!(
        crush_choose_firstn(
            &map,
            -1,
            0,
            1,
            1,
            &mut out,
            0,
            &[0x10000; 4],
            1,
            1,
            0,
            0,
            33,
            1,
            Some(&mut leaves),
            0,
            None,
            None,
        )
        .is_err()
    );
    assert!(crush_do_rule(&map, 0, 0, &mut Vec::new(), i32::MAX as usize + 1, &[]).is_err());
    assert_eq!(calculate_numrep(i32::MIN, i32::MAX as usize), 0);
}

#[test]
fn msr_rejects_overflowing_products_and_limits_undo_to_requested_output() {
    let mut map = map();
    let rule = map.rules[0].as_mut().unwrap();
    rule.rule_type = RuleType::MsrFirstN;
    rule.steps[0].arg1 = -1;
    rule.steps[1] = CrushRuleStep {
        op: RuleOp::ChooseMsr,
        arg1: 65536,
        arg2: 1,
    };
    rule.steps.insert(
        2,
        CrushRuleStep {
            op: RuleOp::ChooseMsr,
            arg1: 65536,
            arg2: 0,
        },
    );
    let mut result = Vec::new();
    assert!(crush_do_rule(&map, 0, 0, &mut result, 1, &[0x10000; 4]).is_err());

    let rule = map.rules[0].as_mut().unwrap();
    rule.steps[0].arg1 = -2;
    rule.steps[1] = CrushRuleStep {
        op: RuleOp::ChooseMsr,
        arg1: i32::MAX,
        arg2: 0,
    };
    rule.steps.remove(2);
    crush_do_rule(&map, 0, 0, &mut result, 1, &[0x10000; 4]).unwrap();
    assert_eq!(result.len(), 1);
    assert!((0..4).contains(&result[0]));
}
