"""Generate source-pinned CRUSH choose-argument vectors.

Usage: python3 rados/tests/crush/reference/generate-choose-args-reference.py ../ceph [--check]
"""
from pathlib import Path
import subprocess as sp
import sys
import tempfile

ceph = Path(sys.argv[1]).resolve()
check = sys.argv[2:] == ["--check"]
reference = Path(__file__).resolve().parent
out_file = reference / "choose-args-vectors.txt"
refs = {
    "quincy": "b12291d110049b2f35e32e0de30d70e9a4c060d2",
    "tentacle": "7f793731f1b39eb4f465e960113d2363c311b964",
}
files = ("crush/mapper.c", "crush/mapper.h", "crush/hash.c", "crush/hash.h",
         "crush/crush.h", "crush/crush_ln_table.h", "crush/crush_compat.h",
         "include/int_types.h")

with tempfile.TemporaryDirectory(prefix="crush-choose-args-reference-") as temporary:
    root = Path(temporary)
    output = {}
    for release, revision in refs.items():
        dest = root / release
        (dest / "include").mkdir(parents=True)
        (dest / "crush").mkdir()
        for name in files:
            (dest / name).write_bytes(sp.check_output([
                "git", "-C", str(ceph), "show", f"{revision}:src/{name}"]))
        (dest / "acconfig.h").touch()
        command = ["clang", "-std=gnu99", "-O2", f"-I{dest}", f"-I{dest / 'crush'}",
                   str(reference / "choose-args-reference.c"), str(dest / "crush/mapper.c"),
                   str(dest / "crush/hash.c"), "-lm", "-o", str(dest / "run")]
        if release == "quincy":
            command.append("-DQUINCY")
        sp.run(command, check=True)
        output[release] = [sp.check_output([str(dest / "run"), str(scenario)], text=True)
                           for scenario in range(5 + 2 * (release == "tentacle"))]

common = "".join(output["quincy"])
assert common == "".join(output["tentacle"][:5]), "Quincy/Tentacle choose vectors differ"
generated = (
    "# Generated by generate-choose-args-reference.py from pinned Ceph C mapper.c.\n"
    "# fields: scenario mode x result-count result-items...; mode 0=absent, 1=empty, 2=selected.\n"
    + common + output["tentacle"][5] + output["tentacle"][6]
)
if check:
    assert out_file.read_text() == generated, "checked-in choose vectors are stale"
else:
    out_file.write_text(generated)
    print(f"wrote {out_file}")
